import type { Metadata } from "next";
import "./landing.css";
import { ClerkProvider } from "@clerk/nextjs";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="fr">
      <head>
        <title>Landing Page</title>
      </head>
      <body>{children}</body>
    </html>
    </ClerkProvider>
  );
}


