import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import ClientProvider from "@/app/meeting/ClientProvider";
import StoreProvider from "@/app/(components)/redux"; // adjust the import path as needed

const inter = Inter({ subsets: ["latin"] });

// Import dynamique avec SSR désactivé pour s'assurer que le composant s'exécute seulement côté client
const ConditionalDashboardWrapper = dynamic(
  () => import("@/app/ConditionalDashboardWrapper"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <title>Project Management</title>
        </head>
        <body className={inter.className}>
          <StoreProvider>
            <ClientProvider>
              <ConditionalDashboardWrapper>
                {children}
              </ConditionalDashboardWrapper>
            </ClientProvider>
          </StoreProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}